language: node_js
node_js:
- '6'
script:
- npm run build
before_deploy:
- cd dist
deploy:
  provider: npm
  email: WOOLAN@piratized.se
  api_key:
    secure: G3qZR0hekmPSTiSMd/2XTeyMYT9N7DWgeNXggxWL+50F7x6KeOUl1SL8b+KJ69qUNFJJcg9bevoJI9zlHuxK6HPD3oP4f/Y2pGFkqVBf0HxFyDXCVq+7E8xHVMrVyVEnGN82z5W9Sh4F8DZggEZyMwZXZ/FeK4oofHdBm62UueZMnX3L1aVWWkRHXk9Nm5t14K4MLr5E37CkNoefUzN7bsFNk8HQRDlihMoxxtV6dOVeolnmPBrkKVv6d3WcOHTarmkw8PzdtCG7CVbmF8u9v3rR9VkIfC641JG604xTBAQXXKpIIVndIKJ4XtQHL2h66e+ffte5NNO2o4QYrBN7LlXB4T0PoxifH2oJm+yLhtdxY/ViCM4WFplr9QY5yl1Zu34q72y1J/rJVJaP4BZGjNJ+/V8q+H1PwT4xSTu5DcaWeXf3gf6bCKGzu8jKsjv9+rXk8uPHR58NRkGqrTX1QWFtg7vkf8YiowG0rZlDnsM0ifFCVa8bv5ohMcrC1fENHHdBqso4Ybu5938EKRD1dpbykOuJpYjaHGrCKYzI8PzkWHGR3UNiixDrLRt5PIe3Uet1iRduUm9Db2nuiIOdnzM44xvT7Ec/1B1IUPhDWlSSm5g9nuRyVwQsbatqdPSfrEQ6EXSXD5kEiUMwepY548cxL2cwXYWnRQ/Y+BRxpyw=
  skip_cleanup: true
  on:
    tags: true
